project:
  type: website
  output-dir: docs
  resources:
      - elizabeth_polito_cv.pdf

website:
  title: "Elizabeth Polito"
  navbar:
    left: []
  page-footer:
    background: light
    center: "E. Polito 2025"

format:
  html:
    theme:
      - flatly
      - custom.scss
    css: styles.css
    toc: true